name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'
  schedule:
    - cron: '0 9 * * *'

jobs:
  unit: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: |
        npm install
        npm run all

  integration: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - core20
          - core22
          - core24
    steps:
    - uses: actions/checkout@v6
    - uses: ./
      id: snapcraft
      with:
        path: './test-projects/${{ matrix.project }}'
    - uses: actions/upload-artifact@v6
      with:
        name: 'snap-${{ matrix.project }}'
        path: ${{ steps.snapcraft.outputs.snap}}
        compression-level: 0
        retention-days: 7

  check-runner: # make sure the action works on each VM image
    strategy:
      matrix:
        runner:
          - ubuntu-22.04
          - ubuntu-24.04
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v6
    - uses: ./
      with:
        path: './test-projects/core22'
